apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fastapi
  namespace: microgrid
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /fastapi(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000

      - path: /esp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-esp-service
            port:
              number: 8000
