# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fastapi-ingress
#   namespace: microgrid
#   annotations:
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: localhost
#     http:
#       paths:
#       - path: /fastapi(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: fastapi-service
#             port:
#               number: 8000


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: microgrid
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /fastapi
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000

      - path: /esp
        pathType: Prefix
        backend:
          service:
            name: fastapi-esp-service
            port:
              number: 8000

